using System;
using UnityEngine;
using Steamworks;

public class SteamManager : MonoBehaviour
{
    private void Awake()
    {
        try
        {
            // Steam'i bažlat (480 = SpaceWar test oyunu ID'si)
            SteamClient.Init(480);
            Debug.Log("Steam Bažlatżldż!");
        }
        catch (Exception e)
        {
            Debug.LogError("Steam HATA: " + e.Message);
        }
    }

    private void Update()
    {
        // Steam'den gelen mesajlarż dinle
        SteamClient.RunCallbacks();
    }

    private void OnApplicationQuit()
    {
        SteamClient.Shutdown();
    }
}